name: diary_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  github_sign_in: ^0.0.5-dev.4
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  emojis: ^0.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
