// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1M2-3eWRXFH8jp1Dond2TMIrJxOi-deQ',
    appId: '1:718853177678:web:b3ccec160fb14f48b45e1f',
    messagingSenderId: '718853177678',
    projectId: 'diaryapp-1e6b9',
    authDomain: 'diaryapp-1e6b9.firebaseapp.com',
    storageBucket: 'diaryapp-1e6b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSSlAXd_drY8Qba95Ehsv4jvawQHQ0sc',
    appId: '1:718853177678:android:436f6de57b92ad11b45e1f',
    messagingSenderId: '718853177678',
    projectId: 'diaryapp-1e6b9',
    storageBucket: 'diaryapp-1e6b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CGqFeWiZ2npCKPi8g695ZhEU3jl1G7w',
    appId: '1:718853177678:ios:56be6e731119beb9b45e1f',
    messagingSenderId: '718853177678',
    projectId: 'diaryapp-1e6b9',
    storageBucket: 'diaryapp-1e6b9.appspot.com',
    iosClientId: '718853177678-aib5s6vn4vnp09urtsqfdrifjijc892t.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CGqFeWiZ2npCKPi8g695ZhEU3jl1G7w',
    appId: '1:718853177678:ios:788248ba06d21820b45e1f',
    messagingSenderId: '718853177678',
    projectId: 'diaryapp-1e6b9',
    storageBucket: 'diaryapp-1e6b9.appspot.com',
    iosClientId: '718853177678-ld0q6bb4to5h858o5j239j1euqv7bi5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp.RunnerTests',
  );
}
